# Generated by Django 4.1 on 2023-01-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_mobile_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_employee_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_mobile_number',
            field=models.IntegerField(),
        ),
    ]
